FROM node:latest as node
WORKDIR /app
COPY . .


RUN npm install -g @nrwl/cli
RUN npm install --force
RUN npx nx build host 
#--configuration=production
#RUN pwd && ls

#stage 2
FROM nginx:alpine
COPY ./apps/first-microfront/nginx.conf /etc/nginx/nginx.conf
COPY --from=node /dist/apps/host /usr/share/nginx/html